version: "3.8"

services:
  attacker:
    build: ./attacker
    container_name: attacker
    networks:
      - testnet
    tty: true
    environment:
      - DEFENDER_HOST=defender
      - DEFENDER_PORT=80
    volumes:
      - ./attacker:/app
    command: tail -f /dev/null

  defender:
    image: nginx:alpine
    container_name: defender
    ports:
      - "8080:80"
    networks:
      - testnet
    restart: unless-stopped
    #security_opt:
    #  - no-new-privileges:true
    cap_drop:
      - ALL
    #tmpfs:
    #  - /tmp:size=64m,mode=1777
    #  - /var/cache/nginx
    volumes:
      - ./defender/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./defender/html:/usr/share/nginx/html:ro
    #sysctls:
    #  - net.ipv4.icmp_echo_ignore_broadcasts=1
    #  - net.ipv4.tcp_syncookies=1
    #  - net.ipv4.conf.all.rp_filter=1
    #environment:
    #  - NGINX_LIMIT_RATE=256k
    #command: ["/bin/bash", "-c", "service nginx start && tail -f /dev/null"]

networks:
  testnet:

volumes:
  nginx_cache:
