services:
  nginx:
    container_name: nginx
    cpus: 0.1
    mem_limit: 64m
    image: nginx:1.27.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    networks:
      - test

  app:
    container_name: app
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - 5000:5000
    stop_signal: SIGINT
    networks:
      - test

  attacker:
    container_name: attacker
    build: ./attacker
    networks:
      - test

networks:
  test:
